import React from 'react';
import { Subtitle, Small, Text } from './terms-of-use-dialog.styled';

export const TermsOfUseDialog = () => {
  return (
    <>
      <Subtitle>Insight Venture Partners Terms of Use</Subtitle>
      <Small>Effective Date: January 23, 2017</Small>
      <Text>PLEASE READ ALL OF THE FOLLOWING TERMS AND CONDITIONS OF USE (“TOU”) FOR THIS WEBSITE BEFORE USING THIS WEBSITE. By continuing to access, link to, or use this Website, including but not limited to text, content, photographs, video, audio and graphics, services, and goods (the “Service”), you signify YOUR ACCEPTANCE OF THE TOU. Insight Venture Management, LLC (“Insight”) reserves the right to modify the TOU at any time by posting a revised TOU on this Website, and such modifications shall be effective immediately. Please continue to review the TOU whenever accessing, linking to, or using this Website, in particular for any updates to the TOU. Your access, link to, or use of the Website, or any service on this Website, after the posting of modifications to the TOU will constitute YOUR ACCEPTANCE OF THE TOU, as modified. If, at any time, you do not wish to accept the TOU, you may not access, link to, or use this Website or the Service.</Text>

      <Subtitle>1. Use and Restrictions:</Subtitle>
      <Text>(a) You represent, warrant, and covenant that you are (i) at least eighteen (18) years old; and (ii) shall use the Service only as set forth in this TOU. You agree to comply with any other applicable terms and conditions of use and legal disclaimers set forth on the Service. When using the Service, you shall not impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity. You represent, warrant, and covenant that you have completed any Insight-imposed registration or approval process necessary to use any password-protected portion of this Website, if required. As part of this registration or approval process, if you have been provided with a unique username and/or password (your unique username and password, the “User ID”) to access parts of the Service, you agree to treat the User ID as confidential and not to disclose such User ID, other than to persons within your organization or household, or other persons agreed to by Insight. You are fully responsible for all usage and activity of the Service through your User ID, including, but not limited to, any use of the Service by you or any third party using your User ID.
<br /><br />
(b) This Website is controlled and operated within the United States. Insight does not make any representations or warranties that the content or materials available on this Website are appropriate, lawful, or available in any foreign countries. Those who choose to access this Website from other countries are responsible for compliance with any and all applicable local laws. You may not export or re-export any content of this Website.
<br /><br />
(c) You acquire absolutely no rights or licenses in or to the Service and materials contained within the Service other than the limited right for you to access and use the Service in accordance with this TOU. You are not permitted to transfer this right.
<br /><br />
(d) Insight grants to you a nonexclusive, nontransferable, and limited license to access and use the Service only as expressly permitted in this TOU. You may not use the Service for any illegal purpose, to facilitate the violation of any law or regulation, or in a manner inconsistent with this TOU. You agree that your use of the Service is solely for your own personal, non-commercial purposes and benefit. You may not copy, reproduce, recompile, decompile, disassemble, reverse engineer, distribute, publish, display, perform, modify, upload to, create derivative works from, transmit, download, or in any way exploit any part of the Service, except as set forth in this TOU or as explicitly specified in the Service. You may download material from the Service and/or make copies of the material from the Service for your own personal, noncommercial use and benefit, provided that you retain all copyright and other proprietary notices. The Service and the information contained therein may not be used to construct a database of any kind. Nor may the Service be stored (in its entirety or in any part) in databases for access by you or any third party to distribute any database services containing all or part of the Service.  You further agree not to use the Website to (i) transmit, or procure the sending of, any advertising or promotional material, including any “junk mail”, “spam” or similar solicitation; and (ii) impersonate or attempt to impersonate Insight, an Insight employee, another user or any other person or entity by using the names, email addresses, social media handles or other information associated with any of the foregoing.
<br /><br />
(e) You may not access, monitor, or copy any content or information on the Service using any robot, spider, scraper, web crawler, or other automated means or any similar manual process. You may not violate the restrictions in any robot exclusion headers on the Service, if any, or bypass or circumvent other measures employed to prevent or limit access to the Service. You may not use the Website in any manner that could disable, overburden, damage or impair the site or interfere with anyone else’s use of the Website. You may not violate the security of the Service or attempt to gain unauthorized access to the Service or computer systems or networks connected to the Service through any means. You may not interfere with any other party’s use and enjoyment of this Website, or any of the content, information, or services provided on this Website.</Text>

      <Subtitle>2. Intellectual Property:</Subtitle>
      <Text>The Service is proprietary and protected by copyrights, trademarks, service marks, international treaties, and/or other proprietary rights and laws of the U.S. and other countries. The Service is also protected as a collective work or compilation under U.S. copyright and other laws and treaties. All content and other elements making up the Service are also copyrighted works. You agree to abide by all applicable copyright and other laws, as well as any additional copyright notices or restrictions contained in the Service. You acknowledge that the Service has been developed, compiled, prepared, revised, selected, and arranged by Insight and others through the application of methods and standards of judgment developed and applied through the expenditure of substantial time, effort, and money and constitutes valuable intellectual property of Insight and such others. You agree to protect the proprietary rights of Insight and all others having rights in the Service during and after the term of this TOU and to comply with all reasonable written requests made by Insight or its suppliers and licensors of content or otherwise (“Suppliers”) to protect their and others’ contractual, statutory, and common law rights in the Service. You agree to notify Insight in writing promptly at Insight Venture Partners, 1114 Avenue of the Americas, 36th Floor, New York, NY, 10036, telephone (212) 230-9200, facsimile (212) 230-9272, e-mail growth@insightpartners.com upon becoming aware of any unauthorized access or use of the Service by any individual or entity or of any claim that the Service infringes upon any copyright, trademark, or other contractual, statutory, or common law rights. All present and future rights in and to trade secrets, patents, copyrights, trademarks, service marks, know-how, and other proprietary rights of any type under the laws of any governmental authority, domestic or foreign, including rights in and to all applications and registrations relating to the Service (the “Intellectual Property Rights”) shall, as between you and Insight, at all times be and remain the sole and exclusive property of Insight. All present and future rights in and title to the Service (including the right to exploit the Service and any portions of the Service over any present or future technology) are reserved to Insight for its exclusive use.
      <br /><br />
You may not use any of Insight’s trademarks, trade names, service marks, copyrights, or logos, in any manner which creates the impression that such items belong to or are associated with you or, except as otherwise provided herein, are used with Insight’s consent, and you acknowledge that you have no ownership rights in or to any of such items. You may use the Insight logo available for public download and use through our Media Kit, provided you abide by the applicable terms and conditions provided in the Media Kit.</Text>

      <Subtitle>3. Disclaimer of Warranties/Limitations on Liability:</Subtitle>
      <Text>YOU AGREE THAT YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK AND ACKNOWLEDGE THAT ALL INFORMATION CONTAINED IN THE SERVICE IS PROVIDED AS IS AND AS AVAILABLE, AND THAT INSIGHT MAKES NO WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE SERVICE, INCLUDING, BUT NOT LIMITED TO, MERCHANTABILITY, NON-INFRINGEMENT, TITLE, OR FITNESS FOR A PARTICULAR PURPOSE OR USE.
      <br /><br />
Insight does not warrant that the Service is compatible with your equipment or that the Service, or e-mail sent by Insight or any of its representatives, is free of errors or viruses, worms or “Trojan horses”, or any other harmful, invasive, or corrupted files, and is not liable for any damage you may suffer as a result of such destructive features. You agree that Insight and its partners, Suppliers, and affiliates and their respective owners, members, agents, directors, officers, employees, representatives, affiliates, successors, and assigns shall have no responsibility or liability for: (i) any injury or damages, whether caused by the negligence of Insight and its partners, Suppliers, and affiliates and their respective owners, members, agents, directors, officers, employees, representatives, affiliates, successors, and assigns or otherwise arising in connection with the Service and shall not be liable for any lost profits, losses, punitive, incidental, or consequential damages, or any claim against Insight; or (ii) any fault, inaccuracy, omission, delay, or any other failure in the Service caused by your computer equipment or arising from your use of the Service on such equipment. YOU ASSUME ALL RESPONSIBILITIES AND OBLIGATIONS WITH RESPECT TO ANY DECISIONS OR ADVICE MADE OR GIVEN AS A RESULT OF THE SERVICE, INCLUDING WITHOUT LIMITATION ANY DECISION MADE OR ACTION TAKEN BY YOU IN RELIANCE UPON THE SERVICE.
<br /><br />
The content of other websites, services, or goods that may be linked to or from the Service is not maintained or controlled by Insight. Insight is therefore not responsible for the availability, content, or accuracy of other websites, services, or goods that may be linked to or from the Service. Insight does not: (a) make any warranty, express or implied, with respect to the use of the links provided on, or to, the Service; (b) guarantee the accuracy, completeness, usefulness or adequacy of any other websites, services, or goods, that may be linked to or from the Service; or (c) make any endorsement, express or implied, of any other websites, services, or goods, that may be linked to or from the Service.
<br /><br />
Insight is also not responsible for the reliability or continued availability of the telephone lines, wireless services, communications media, and equipment you use to access the Service. You understand that Insight and/or third-party contributors to the Service may choose at any time to inhibit or prohibit their content from being accessed under this TOU. Anything to the contrary herein set forth notwithstanding, Insight and its partners, Suppliers, and affiliates and their respective owners, members, agents, directors, officers, employees, representatives, affiliates, successors, and assigns shall not, directly or indirectly, be liable, in any way, to you or any other person for any: (x) inaccuracies or errors in or omissions from the Service; (y) delays, errors, or interruptions in the transmission or delivery of the Service; or (z) loss or damage therefrom or occasioned thereby, or by any reason of nonperformance.
<br /><br />
UNDER NO CIRCUMSTANCES, INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE, SHALL INSIGHT AND ITS PARTNERS, SUPPLIERS, AND AFFILIATES AND THEIR RESPECTIVE OWNERS, MEMBERS, AGENTS, DIRECTORS, OFFICERS, EMPLOYEES, REPRESENTATIVES, AFFILIATES, SUCCESSORS, AND ASSIGNS BE LIABLE TO YOU OR ANY THIRD PARTY FOR DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, PUNITIVE, OR EXEMPLARY DAMAGES EVEN IF INSIGHT HAS BEEN ADVISED SPECIFICALLY OF THE POSSIBILITY OF SUCH DAMAGES, ARISING FROM USE OF OR INABILITY TO USE THE SERVICE OR ANY LINKS OR ITEMS ON THE SERVICE OR ANY PROVISION OF THIS TOU. APPLICABLE LAW MAY NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY OR INCIDENTAL OR CONSEQUENTIAL DAMAGES.
<br /><br />
You accept that Insight has the right to change the content or technical specifications of any aspect of the Service at any time in Insight’s sole discretion. You further accept that such changes may result in your being unable to access the Service.</Text>

      <Subtitle>4. Linking and Framing:</Subtitle>
      <Text>You may not frame this Website. Without limiting other provisions contained in this TOU, you may include a link(s) on your website to this Website’s publicly accessible Web pages (i.e., any web pages that do not require a login and password and/or restrict access). Upon linking to this Website pursuant to the TOU, you will be granted a nonexclusive, non-transferable, royalty-free sub-license to use the INSIGHT mark identified in the Media Kit solely for providing an underlined, textual link from your website to insightpartners.com.
      <br /><br />
You may not link to this Website from any website containing objectionable, embarrassing, inappropriate, profane, defamatory, infringing, obscene, indecent, or unlawful topics, names, material, or information that violates any applicable intellectual property, proprietary, privacy, or publicity rights. If you link to this Website, you may not portray any person or subject in a false or misleading light. In addition, you may not imply that Insight is endorsing your or any other person’s products or services.</Text>

      <Subtitle>5. Indemnification:</Subtitle>
      <Text>You agree, at your own expense, to indemnify, defend and hold harmless Insight and its partners, Suppliers, and affiliates and their respective owners, members, agents, directors, officers, employees, representatives, affiliates, successors, and assigns against any claim, suit, action, or other proceeding, from and against any and all claims, damages, liabilities, costs, and expenses, including reasonable attorneys’ and experts’ fees, arising out of or in connection with the Service, or any links on the Service, including, but not limited: (i) any breach or violation of this TOU by you or someone using your computer; (ii) material entered into or transmitted through the Service with the use of your computer; (iii) your use, or someone else’s directing your computer’s use, of the Service; (iv) a claim that any use of the Service by you or someone using your computer infringes any Intellectual Property Right of any third party, or any right of privacy or publicity, is libelous or defamatory, or otherwise results in injury or damage to any third party; or (v) any deletions, additions, insertions, or alterations to, or any unauthorized use of, the Service by you or someone using your computer. You agree to pay any and all costs, damages, and expenses, including, but not limited to, reasonable attorneys’ fees and costs awarded against or otherwise incurred by or in connection with or arising from any such claim, suit, action, or proceeding attributable to any such claim. Insight reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will fully cooperate with Insight in asserting any available defense.</Text>

      <Subtitle>6. Term and Termination:</Subtitle>
      <Text>(a) You may terminate the TOU as it applies to you, with or without cause and at any time, by discontinuing your use of the Service.
      <br />
(b) Insight shall have the right to immediately terminate the TOU in the event of any breach by you of the TOU. Insight may discontinue the Service, or change its availability to you, at any time in Insight’s sole discretion. You accept that Insight has the right to change the content or technical specifications of any aspect of the Service at any time in Insights sole discretion. You further accept that such changes may result in your being unable to access the Service.
<br />
(c) Insight shall not be liable to you or any third party for the termination or suspension of the Service, or any claims related to the termination or suspension of the Service. Upon termination of the TOU by you or Insight, you must discontinue your use of the Service and destroy promptly all materials obtained from the Service and any copies thereof.</Text>

      <Subtitle>7. Governing Law:</Subtitle>
      <Text>The TOU shall be governed and construed in accordance with the laws of the United States and the State of New York, without giving effect to conflicts-of-law principles thereof. You agree to submit to the personal jurisdiction of the state and federal courts located in New York County in the State of New York with respect to any legal proceedings that may arise in connection with the Service or from a dispute as to the interpretation or breach of the TOU.</Text>

      <Subtitle>8. General:</Subtitle>
      <Text>The TOU and any other terms and conditions of service or legal disclaimers on the Service constitute the entire agreement between you and Insight and govern your use of the Service. The section titles in the TOU are used solely for the convenience of you and Insight and have no legal or contractual significance. The failure of Insight to exercise or enforce any right or provision of the TOU shall not constitute a waiver of such right or provision. If any provision of the TOU is found invalid or unenforceable, that provision will be enforced to the maximum extent permissible, and the other provisions of the TOU will remain in force. You may not assign the TOU or the rights hereunder without the prior written consent of Insight. Sections 1(a), 1(b), 1(c), 2 through 5, 6(c), and 7 through 9 shall survive termination or expiration of this TOU.</Text>

      <Subtitle>9. Privacy Policy:</Subtitle>
      <Text>Click here for this Website’s privacy policy.</Text>

      <Subtitle>10. Copyright Agent for Copyright Infringement Claims (Digital Millennium Copyright Act):</Subtitle>
      <Text>The designated agent to receive notification of claimed infringement under Title II of the Digital Millennium Copyright Act is: Eric Goldstein, Insight Venture Management, LLC, 1114 Avenue of the Americas, 36th Floor, New York, NY, 10036, telephone (212) 230-9200, facsimile (212) 230-9272, e-mail growth@insightpartners.com.</Text>
    </>
  );
}
